sudo: required

languages: python

python:
  - "3.6"

before_install:
  - "sudo apt-get purge openjdk-6*"
  - "sudo apt-get purge openjdk-7*"
  - "sudo apt-get purge oracle-java7-*"
  # - "sudo apt-get purge python2.7"
  # - "nvm install 6; nvm alias default node"
  - "sudo useradd localstack -s /bin/bash"
  - "mkdir ~/.aws"
  - "echo '[profile localstack]' >> ~/.aws/config"
  - "echo 'output = text' >> ~/.aws/config"
  - "echo 'region = ap-northeast-1' >> ~/.aws/config"
  - "echo '[localstack]' >> ~/.aws/credentials"
  - "echo 'aws_access_key_id = dummy' >> ~/.aws/credentials"
  - "echo 'aws_secret_access_key = dummy' >> ~/.aws/credentials"

addons:
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    - AWS_DEFAULT_REGION=ap-northeast-1

install:
  - make localstack
  - make awscli

script:
  - make test
